version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
      
  service1:
    build: ./service1
    container_name: "service1"
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      
  service2:
    build: ./service2
    container_name: "service2"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379